version: '2'
services:
  main:
    container_name: facter_large_test
    image: mkuculyma/alpine-python-facter:latest
    network_mode: "host"
    volumes:
      - ${PLUGIN_SRC}:/snap-plugin-collector-facter
    entrypoint: sh -c 'python /snap-plugin-collector-facter/scripts/test/large.py'